---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Register the output of the 'uptime' command
      command: uptime
      register: system_uptime

    - name: Print the registered output of the 'uptime' command
      debug:
        var: system_uptime.stdout
