---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubunto-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10
        
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2

      - name: Install test dependencies
        run: pip3 install molecule docker yamllint ansible-lint

      - name: run molecule test