---
- hosts: all
  become: true
  
  handlers:
    - import_tasks: handlers/apache.yml


  # funktioniert auch mit default Variablen und Modul include_vars (Folge 5, min 47)     
  vars_files:
    - vars/{{ ansible_os_family }}.yml
  
  tasks:
    - import_tasks: tasks/apache.yml
  # Alternative:  include kann mit dynamischen tasks umgehen, die mit Variablen arbeiten
  # - include_tasks: tasks/apache.yml
    

    