Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disable:true
  config.vm.provider :virtualbox do |v|
    v.memory = 3000
    v.linked_clone = true
  end

  # solr server 
  config.vm.define "solr" do |solr|
    solr.vm.hostname = "orc-solr.test"
    solr.vm.network :private_network, ip:"192.168.60.10"
  end

end
