---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    # syntax check will pass wheter or not this file exists
    - include_tasks: dates.yml

    # This will cause a failure, since it can be checked statically
    #- import_tasks: free.yml

    - name: Print a debug message
      debug:
        msg: "Hello there"