Vagrant.configure("2") do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disable:true
    centos.vm.hostname = "centos-machine"
    centos.vm.network "private_network", ip: "192.168.60.11"
    centos.vm.provider "virtualbox" do |vb|
      vb.memory = 1000
      vb.linked_clone = true
      vb.name = "centos"
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disable:true
    ubuntu.vm.hostname = "ubuntu-machine"
    ubuntu.vm.network "private_network", ip: "192.168.60.12"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = 1000
      vb.linked_clone = true
      vb.name = "ubuntu"
    end
  end
end
